// TiendaReact/src/App/components/login.jsx
import React from 'react';
import { Route, Redirect, Link } from "react-router-dom";
import request from 'superagent';
import Tienda from './catalogo.jsx'


class Login extends React.Component{

    constructor(props) {
      super(props);
      this.state = {
        valueUser: '',
        valuePass: '',
        login: false
      };

      this.handleChange = this.handleChange.bind(this);
      this.handleSubmit = this.handleSubmit.bind(this);
    }

    handleChange(event){
      if(event.target.id == 'user'){
        this.setState({valueUser: event.target.value});
      }else{
        this.setState({valuePass: event.target.value});
      }
    }

    handleSubmit(event) {
      event.preventDefault();
      request.post('http://localhost:3000/api/users/login')
      .send({ user: this.state.valueUser, pass: this.state.valuePass })
      .end((err, res) => {
          const response = JSON.parse(res.text).status;
          if(response == 'Validado'){
            //<Route exact path="/" render={() => ( <Redirect to="/tienda"/> )  }/>
            //<Redirect to={{pathname: "/tienda"}} />;
            this.setState({login: true});
            alert(response);
          }else if(response == 'Contraseña incorrecta'){
            document.getElementById('labelUser').style.display = 'none';
            document.getElementById('labelPass').style.display = 'flex';
          }else if(response == 'Usuario no registrado'){
            document.getElementById('labelUser').style.display = 'flex';
            document.getElementById('labelPass').style.display = 'none';

          }
          if(err != null){
            console.log(err);
          }
      });

    }

    render(){
        if (this.state.login){
          return <Redirect to='/tienda'/>
        }
        return(
          <div className="row mainContainer">
            <div className="col s5 loginContainer center-align">
              <div className="loginTitle">Inicio de Sesión</div>
              <div className="fields-Container">
                <form className="" action="index.html" method="post" onSubmit={this.handleSubmit}>
                  <input className="inputLogin" type="text" id="user" value={this.state.valueUser} onChange={this.handleChange} placeholder="Usuario..."/>
                  <label className="alertMessage" id="labelUser">Usuario no registrado</label>
                  <input className="inputLogin" type="password" id="pass" value={this.state.valueUSer} onChange={this.handleChange} placeholder="Contraseña..."/>
                  <label className="alertMessage" id="labelPass">Contraseña incorrecta</label>

                  <button type="submit" className="button loginButton">Ingresar</button>
                </form>
              </div>
            </div>
          </div>
        );
        }
}

export default Login;

// TiendaAngular/client/src/app/login-component/login-component.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { HttpService } from '../http.service'
import { FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'app-login-component',
  templateUrl: './login-component.component.html',
  styleUrls: ['./login-component.component.css'],
  providers: [ HttpService ]
})
export class LoginComponent implements OnInit {
  miFormulario: FormGroup;
  userNull = false;
  incorrectPassword = false;

  constructor(private router: Router, private httpService: HttpService) {}

  ngOnInit() {
    this.miFormulario = new FormGroup({
      'user': new FormControl('', Validators.required),
      'password': new FormControl('', Validators.required)
    })
  }

  onLogin(){
    let user = this.miFormulario.value.user;
    let password = this.miFormulario.value.password;
    this.validateLogin(user, password);
  }

  validateLogin(user: any, pass: any){
    this.httpService.loginUser(user, pass)
    .subscribe(
      (res: HttpResponse<any>) => {
        
        let respuesta = res.status;
        if(respuesta.toString() == 'Validado'){
          this.router.navigate(['home']);
        }else if(respuesta.toString() == 'Contraseña incorrecta'){
          console.log(respuesta);
          this.incorrectPassword = true;
          this.userNull = false;
        }else if(respuesta.toString() == 'Usuario no registrado'){
          console.log(respuesta);
          this.userNull = true;
        }
      })
  }

}

<div class="row mainContainer">
  <div class="col s5 loginContainer center-align">
    <div class="loginTitle">Inicio de Sesión</div>
    <div class="fields-Container">
      <form class="" action="index.html" method="post" [formGroup]="miFormulario" (ngSubmit)="onLogin()">
        <input type="text" formControlName="user" placeholder="Usuario..."/>
        <label class="alertMessage" *ngIf="userNull">Debe ingresar un usuario existente</label>
        <input type="password" formControlName="password" placeholder="Contraseña..."/>
        <label class="alertMessage" *ngIf="incorrectPassword">Contraseña incorrecta</label>

        <button type="submit" class="button loginButton" [disabled]="!miFormulario.valid">Ingresar</button>
      </form>
    </div>
  </div>
</div>
