// TiendaAngular/client/src/app/card-producto/card-producto.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductoHttpService } from '../producto-http.service';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { Router } from '@angular/router';


@Component({
  selector: 'app-card-producto',
  templateUrl: './card-producto.component.html',
  styleUrls: ['./card-producto.component.css']
})
export class CardProductoComponent implements OnInit {
  private productos : any[] = [];

  constructor(private productoService: ProductoHttpService, private router: Router) { }

  ngOnInit() {
    const prod = this.productoService.getProd();
    prod.subscribe((prodData: any[]) => {
      this.productos = prodData;
    })
  }
}

<div class="contenedorProducto" *ngFor="let prod of productos">
  <div class="col s3">
    <div class="card">
      <div class="card-image" >
        <img src="{{prod.url}}" alt="{{prod.nombre}}">
      </div>
      <div class="card-content">
        <span class="card-title">{{prod.nombre}}</span>
        <span><strong>Precio: </strong><span class="contenidoSpan">${{prod.precio}}</span></span>
        <br>
        <span><strong>Unidades disponibles: </strong><span class="contenidoSpan">{{prod.cantidadDisponible}}</span></span>
      </div>
      <div class="card-action">
        <a [routerLink]="['/producto', prod.nombre]">Ver más</a>
        <a href="#">Añadir</a>
        <input type="number" name="cantidadSelec" min="1" max="{{prod.cantidadDisponible}}">
        <router-outlet></router-outlet>
      </div>
    </div>
  </div>
</div>

// TiendaReact/src/App/components/cardProducto.jsx
import React from 'react';
import { Route, Redirect, Link } from "react-router-dom";

class CrearCardProducto extends React.Component{
  constructor(props){
    super(props);

    this.state = {
      carrito: []
    }
    this.agregarproducto = this.agregarproducto.bind(this);
  }

  agregarproducto(producto){
    this.state.carrito.push(producto)
    console.log(this.state.carrito);
  }

  render(){
    let productos = this.props.producto;
    let carro = [];
    let agregar = (nombre) =>{
      let cantidadSelec = document.getElementById(`${'selec'}${nombre}`).value;
      let producto = {
        nombre: nombre,
        cantidadSelec: cantidadSelec
      }
      this.agregarproducto(producto);
    }

    const listProd = productos.map((item)=>

    <div className="col s3 card cardPr" key={item.nombre}>

          <div className="card-image" >
            <img src={item.url} alt={item.nombre} />
          </div>
          <div className="card-content">
            <span className="card-title titleProd">{item.nombre}</span>
            <span><strong>Precio: </strong><span className="contenidoSpan">${item.precio}</span></span>
            <br />
            <span><strong>Unidades disponibles: </strong><span className="contenidoSpan">{item.cantidadDisponible}</span></span>
          </div>
          <div className="card-action">
            <Link to={`${'/producto'}/${item.nombre}`}>Ver más</Link>
            <a id="btnAdd" onClick={() => agregar(item.nombre)}>Añadir</a>
            <input className="black-text" type="number" id={`${'selec'}${item.nombre}`} min="1" max={item.cantidadDisponible} defaultValue="1" />
          </div>
    </div>

    );
    return listProd;
  }
}

export default CrearCardProducto;
