// TiendaAngular/client/src/app/carrito/carrito.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { Router } from '@angular/router';

import { NavbarComponent } from '../navbar/navbar.component';

import { CarritoService } from '../carrito.service';
import { ProductoHttpService } from '../producto-http.service';

@Component({
  selector: 'app-carrito',
  templateUrl: './carrito.component.html',
  styleUrls: ['./carrito.component.css']
})
export class CarritoComponent implements OnInit {
  private productos: any[] = [];
  private precioTotal = 0;
  private carritoVacio = false;
  constructor(private productoService: ProductoHttpService, private router: Router, private carrito: CarritoService) {}

  ngOnInit() {
    if(this.carrito.getCarrito().length == 0){
      alert('No tienes productos en el carrito.');
      this.carritoVacio = true;
      //this.router.navigate(['/home']);
    }else{
      this.getInfoProd();
      this.carritoVacio = false;
    }
  }
  
  getInfoProd(){
    let carrito = this.carrito.getCarrito();
    const prod = this.productoService.getProd();

    prod.subscribe((prodData: any[]) => {
      for(let key in prodData){
        for(let keyC in carrito){
          if(prodData[key].nombre == carrito[keyC].nombre){
            let carritoDef = {
              nombre: prodData[key].nombre,
              url: prodData[key].url,
              cantidadSelec: carrito[keyC].cantidadSelec,
              cantidadRestante: prodData[key].cantidadDisponible-carrito[keyC].cantidadSelec,
              precio: prodData[key].precio*carrito[keyC].cantidadSelec
            }
            this.precioTotal = this.precioTotal+carritoDef.precio;
            this.productos.push(carritoDef);
          }
        }
      }
      console.log(this.precioTotal);
    })
    //console.log(this.productos);
  }

  cancelarCompra(){
    this.router.navigate(['/home']);
    //this.resetCarrito();
    this.carrito.resetCarrito();
    this.carrito.resetNumProd();
  }

  hacerCompra(){
      for(let key in this.productos){
        const nombre = this.productos[key].nombre;
        const cantidadRes = this.productos[key].cantidadRestante;
        this.productoService.updateProd(nombre, cantidadRes)
        .subscribe((res: HttpResponse<any>) => {
          let respuesta = res.status;
          if(respuesta.toString() == 'actualizado'){
            alert('Compra realizada con exito');
            this.router.navigate(['/home']);
            this.carrito.resetCarrito();
            this.carrito.resetNumProd();
          }else{
            alert(respuesta);
          }
        })
      }
  }

}

<div class="row mainContainer">
  <div class="container">
    <app-navbar></app-navbar>
    <div class="col s12 card">
      <div class="card-title">
        <h3>Carrito de Compras</h3>
      </div>
      <div class="" *ngIf="carritoVacio">
        <h5>No tienes productos en tu carrito.</h5>
      </div>
      <div class="" *ngIf="carritoVacio == false">
        <div class="col s6">
          <ul class="collection" *ngFor="let prod of productos">
            <li class="collection-item avatar">
              <img src="{{prod.url}}" alt="{{prod.nombre}}" class="circle">
              <span class="title">{{prod.nombre}}</span>
              <p>
                <span>Nombre: <span class="contSpan">{{prod.nombre}}</span></span>
                <br>
                <span>Cantidad: <span class="contSpan">{{prod.cantidadSelec}}</span></span>
                <br>
                <span>Precio: <span class="contSpan">${{prod.precio}}</span></span>
              </p>
            </li>
          </ul>
        </div>        
      </div>
      <div class="col s6">
        <div class="card-content">
          <h5>Precio Total: ${{precioTotal}}</h5>
        </div>
        <div class="btnGroup">
          <a (click)="cancelarCompra()" class="btn blue lighten-4">Cancelar</a>
          <a (click)="hacerCompra()" class="btn blue lighten-4">Pagar</a>
        </div>
      </div>
      <router-outlet></router-outlet>
    </div>
  </div>
</div>

// TiendaReact/src/App/components/carrito.jsx
import React from 'react';
import CrearCardProducto from './cardProducto.jsx';
import Navbar from './navbar.jsx';
import { Route, Redirect, Link } from "react-router-dom";
import request from 'superagent';

class Carrito extends React.Component{
  constructor(props){
    super(props);

    this.state = {
      listaCarro: [],
      precioTotal: 0,
      backToHome: false,
      contador: 0
    }

    this.cancelarCompra = this.cancelarCompra.bind(this);
    this.hacerCompra = this.hacerCompra.bind(this);
  }

  componentDidMount(){
    let localSt = JSON.parse(localStorage.getItem('carroTemp'));
    //this.setState({listaCarro: localSt});
    let carrito = [];
    request.get('http://localhost:3000/api/productos/')
    .end((err, res) => {
      const response = JSON.parse(res.text);
      for(let key in response){
        for(let keyC in localSt){
          if(response[key].nombre == localSt[keyC].nombre){
            let carritoDef = {
              nombre: response[key].nombre,
              url: response[key].url,
              cantidadSelec: localSt[keyC].cantidadSelec,
              cantidadRestante: response[key].cantidadDisponible-localSt[keyC].cantidadSelec,
              precio: response[key].precio*localSt[keyC].cantidadSelec
            }
            carrito.push(carritoDef);
            this.setState((state)=>{
              return {
                precioTotal: state.precioTotal+carritoDef.precio
              };
            });
          }
        }
      }
      this.setState({listaCarro: carrito, contador: carrito.length})
      console.log(this.state.precioTotal);
    })

  }

  cancelarCompra(){
    this.setState({listaCarro: [], precioTotal: 0, backToHome: true, contador: 0});
    localStorage.setItem('carroTemp', JSON.stringify([]));
    alert('Compra cancelada');
  }

  hacerCompra(){
    let carro = this.state.listaCarro;
    for(let key in carro){
      const nombre = carro[key].nombre;
      const cantidadRes = carro[key].cantidadRestante;
      request.post('http://localhost:3000/api/productos/update')
      .send({ nombre: nombre, cantidad: cantidadRes })
      .set('X-API-Key', 'foobar')
      .set('accept', 'json')
      .end((err, res) => {
        let respuesta = res.status;
        if(respuesta.toString() == 200){
          alert('Compra realizada con exito');
          this.setState({listaCarro: [], precioTotal: 0, backToHome: true, contador: 0});
          localStorage.setItem('carroTemp', JSON.stringify([]));
        }else{
          alert(respuesta);
        }
      })
    }
  }

  render(){
    if (this.state.backToHome){
      return <Redirect to='/tienda'/>
    }
    return(
      <div className="row mainContainer">
        <div className="container">
          <Navbar cont={this.state.contador}/>
          <div className="col s12 card">
            <div className="card-title">
              <h3>Carrito de Compras</h3>
            </div>
            <div className="" >
              <div className="col s6">
                <ListProductos productos={this.state.listaCarro}/>
              </div>
            </div>
            <div className="col s6">
              <div className="card-content">
                <h5>Precio Total: ${this.state.precioTotal}</h5>
              </div>
              <div className="btnGroup">
                <a onClick={this.cancelarCompra} className="btn blue lighten-4">Cancelar</a>
                <a onClick={this.hacerCompra} className="btn blue lighten-4">Pagar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

function ListProductos(props){
  let productos = props.productos;

  const listProd = productos.map((item)=>
    <li className="collection-item avatar" key={item.nombre}>
      <img src={item.url} alt={item.nombre} className="circle" />
      <span className="title">{item.nombre}</span>
      <p>
        <span>Nombre: <span className="contSpan">{item.nombre}</span></span>
        <br />
        <span>Cantidad: <span className="contSpan">{item.cantidadSelec}</span></span>
        <br />
        <span>Precio: <span className="contSpan">${item.precio}</span></span>
      </p>
    </li>
  );
  return (
    <ul className="collection">{listProd}</ul>
  );

}

export default Carrito;
