// TiendaAngular/client/src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {
  titulo = 'La Bodega';
  barraNav : object[];

  constructor(private router: Router) { }

  ngOnInit() {
    this.barraNav= [
      {
        nombre: 'cerrar sesión',
        iconName: 'exit_to_app',
      },
      {
        nombre: 'carrito',
        iconName: 'shopping_cart',
      },
      {
        nombre: 'catalogo',
        iconName: 'apps',
      }
    ]
  }

  onEvent(idTarget: string){
    if(idTarget == "cerrar sesión"){
        this.router.navigate(['']);
        alert("Chao");
    }else{
      alert("Otro");
    }
  }

  onShopping(){
    alert("Carrito");
  }

  onHome(){
    this.router.navigate(['home']);
  }

}

<nav>
  <div class="nav-wrapper blue lighten-5">
    <span class="brand-logo black-text">{{titulo}}</span>
    <ul id="nav-mobile" class="right hide-on-med-and-down" *ngFor="let item of barraNav">
      <li><a (click)="onEvent(item.nombre)" title="{{item.nombre}}"> <i class="material-icons black-text">{{item.iconName}}</i></a></li>
    </ul>
  </div>
</nav>

// TiendaReact/src/App/components/navbar.jsx
import React from 'react';
import { Route, Redirect, Link } from "react-router-dom";

class Navbar extends React.Component{

  constructor(props){
    super(props);

    this.state = {
      titulo: 'La Bodega',
      numClick: 0
    }
  }

    render(){
        return(
          <nav>
            <div className="nav-wrapper blue lighten-5">
              <span className="brand-logo black-text">{this.state.titulo}</span>
              <OptionsNavbar />
            </div>
          </nav>
        );
    }
}

function OptionsNavbar(){
  let barraNav= [
    {
      nombre: 'cerrar sesión',
      iconName: 'exit_to_app',
      redirect: '/'
    },
    {
      nombre: 'carrito',
      iconName: 'shopping_cart',
      redirect: '/carrito'
    },
    {
      nombre: 'catalogo',
      iconName: 'apps',
      redirect: '/tienda'
    }
  ]

  const listItems = barraNav.map((item)=>
      <li key={item.nombre}><Link to={item.redirect} title={item.nombre}> <i className="material-icons black-text">{item.iconName}</i></Link></li>
  );


  return (
    <ul id="nav-mobile" className="right hide-on-med-and-down">{listItems}</ul>
  );

}

export default Navbar;
