// TiendaAngular/client/src/app/producto/producto.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductoHttpService } from '../producto-http.service';
import { ActivatedRoute } from '@angular/router';
import { Router } from '@angular/router';
import { Location } from '@angular/common';
import { NavbarComponent } from '../navbar/navbar.component';

@Component({
  selector: 'app-producto',
  templateUrl: './producto.component.html',
  styleUrls: ['./producto.component.css']
})
export class ProductoComponent implements OnInit {
  private producto: any[] = [];

  constructor(
    private route: ActivatedRoute,
    private productoService: ProductoHttpService,
    private location: Location,
    private router: Router
  ) { }

  ngOnInit() {
    this.getInfoProd();
  }

  getInfoProd() {
    const name = this.route.snapshot.paramMap.get('nombre');
    const getProd = this.productoService.getProd();

    getProd.subscribe((prodData: any[]) => {
      let aux : any[] = [];
      for(let key in prodData){
        if(prodData[key].nombre == name){
          this.producto = prodData[key];
        }
      }
    })
  return this.producto;
}

}

<div class="row mainContainer">
  <div class="container">
    <app-navbar></app-navbar>
    <div class="col s12 card horizontal">
      <div class="divider"></div>
        <div class="card-image" >
          <img src="{{producto.url}}" alt="{{producto.nombre}}">
        </div>
        <div class="card-stacked">
          <div class="card-title">
            <h2>{{producto.nombre}}</h2>
          </div>
          <div class="card-content">
            <span>{{producto.descripcion}}</span>
            <br>
            <span><strong>Precio: </strong><span class="contenidoDB">${{producto.precio}}</span></span>
            <br>
            <span><strong>Unidades disponibles: </strong><span class="contenidoDB">{{producto.cantidadDisponible
}}</span></span>
          </div>
          <div class="card-action">
            <a [routerLink]="['/home']">Volver</a>
            <a href="#">Añadir</a>
            <input type="number" name="cantidadSelec" min="1" max="{{producto.cantidadDisponible}}">
          </div>
        </div>
      <router-outlet></router-outlet>
    </div>
  </div>
</div>

// TiendaReact/src/App/components/producto.jsx
import React from 'react';
import { Route, Redirect, Link } from "react-router-dom";
import Navbar from './navbar.jsx';
import request from 'superagent';


class Product extends React.Component{
    constructor(){
        super();
        this.state = {
            producto: []
        };
    }

    componentDidMount(){
      const { nombre } = this.props.match.params

      request.get('http://localhost:3000/api/productos/')
      .end((err, res) => {
        const response = JSON.parse(res.text);
        for(let key in response){
          if(response[key].nombre == nombre){
            this.setState({producto: response[key]});
            console.log(this.state.producto);
          }
        }
      })
    }

    render(){
        return(
          <div className="row containerCard">
            <div className="container">
              <Navbar />
              <div className="col s12 card horizontal">
                <div className="divider"></div>
                  <div className="card-image" >
                    <img src={this.state.producto.url} alt={this.state.producto.nombre} />
                  </div>
                  <div className="card-stacked">
                    <div className="card-title">
                      <h2>{this.state.producto.nombre}</h2>
                    </div>
                    <div className="card-content">
                      <span>{this.state.producto.descripcion}</span>
                      <br />
                      <span><strong>Precio: </strong><span className="contenidoDB">${this.state.producto.precio}</span></span>
                      <br />
                      <span><strong>Unidades disponibles: </strong><span className="contenidoDB">{this.state.producto.cantidadDisponible}</span></span>
                    </div>
                    <div className="card-action">
                      <Link to="/tienda">Volver</Link>
                    </div>
                  </div>
              </div>
            </div>
          </div>
      )
  }
}

export default Product;
